server:
  port: ${PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/members/**

        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/attendance/**

        - id: contest-service
          uri: lb://CONTEST-SERVICE
          predicates:
            - Path=/api/contests/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}